// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { ICircuit1Verifier } from "../interfaces/ICircuit1Verifier.sol";

interface IHonkVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external returns (bool);
}

/// @title HonkCircuit1Verifier
/// @notice Adapts the Barretenberg UltraHonk Solidity verifier (generated by bb write_solidity_verifier)
///         to the ICircuit1Verifier interface consumed by CreditVerifier.
///
/// ─── Deployment ─────────────────────────────────────────────────────────────
///
/// The companion HonkUltraVerifier.sol (circuits/circuit1/contracts/HonkUltraVerifier.sol)
/// must be compiled and deployed separately from the main Foundry build because
/// its circuit size (N=4194304, 2^22) requires a dedicated compilation pipeline
/// to avoid Yul stack-depth limits.  The current artifact was generated with:
///
///   cd circuits/circuit1
///   nargo compile                                     # nargo 1.0.0-beta.15
///   bb write_vk -s ultra_honk -b target/circuit1.json -o target/vk --oracle_hash keccak
///   bb write_solidity_verifier -s ultra_honk -k target/vk/vk \
///       -o contracts/HonkUltraVerifier.sol --optimized
///
/// Deploy HonkUltraVerifier.sol first, then deploy this contract passing its address.
/// During development and testing MockCircuit1Verifier is used instead.
///
/// ─── Circuit Parameters ─────────────────────────────────────────────────────
///
///   N                     = 4194304 (2^22)
///   NUMBER_OF_PUBLIC_INPUTS = 114
///   MAX_N (receipts)      = 64
///
/// ─── Public Input Layout ────────────────────────────────────────────────────
///
/// The Noir circuit declares (in order):
///   n                  pub u32         -- 1 field element
///   accumulator_root   pub [u8; 32]    -- 32 field elements (one per byte)
///   capability_hash    pub [u8; 32]    -- 32 field elements
///   adapter_filter     pub [u8; 32]    -- 32 field elements (zero-padded address)
///   min_return_bps     pub u64         -- 1 field element
///                                       = 98 semantic elements
///
/// UltraHonk ZK variant appends 16 aggregation/hiding elements.
/// Total: NUMBER_OF_PUBLIC_INPUTS = 114.
///
/// ─── Proof Encoding ─────────────────────────────────────────────────────────
///
/// The `proof` bytes passed to `verify` must be:
///   abi.encode(bytes honkProof, bytes32[16] zkPublicInputs)
///
/// where:
///   honkProof        The raw binary output of `bb prove --oracle_hash keccak`.
///   zkPublicInputs   The last 16 values from the `public_inputs` file output
///                    by `bb prove`. These are the ZK aggregation commitments
///                    needed by the verifier; they are opaque to CreditVerifier.

contract HonkCircuit1Verifier is ICircuit1Verifier {

    /// @dev NUMBER_OF_PUBLIC_INPUTS from the generated HonkVerifier.sol.
    uint256 private constant _N_PUB = 114;
    uint256 private constant _N_SEMANTIC = 98;   // n(1) + root(32) + cap(32) + adapt(32) + bps(1)
    uint256 private constant _N_ZK_AGG   = 16;   // UltraHonk ZK aggregation elements

    IHonkVerifier public immutable honkVerifier;

    constructor(address _honkVerifier) {
        honkVerifier = IHonkVerifier(_honkVerifier);
    }

    /// @inheritdoc ICircuit1Verifier
    function verify(
        bytes calldata proof,
        PublicInputs calldata inputs
    ) external override returns (bool) {
        // The caller encodes: (bytes honkProof, bytes32[16] zkPublicInputs)
        (bytes memory honkProof, bytes32[_N_ZK_AGG] memory zkAgg) =
            abi.decode(proof, (bytes, bytes32[16]));

        bytes32[] memory pub = _buildPublicInputs(inputs, zkAgg);

        return honkVerifier.verify(honkProof, pub);
    }

    // ────────────────────────────────────────────────────────────────────────

    /// @dev Converts structured PublicInputs + ZK aggregation values to the flat
    ///      bytes32[114] array expected by the Honk verifier.
    ///
    /// Encoding rules (matching Noir's serialization):
    ///   - Scalar integers (u32, u64): one field element = bytes32(value).
    ///   - [u8; 32] arrays: 32 field elements, each bytes32(uint256(byte_value)).
    ///
    /// The adapter_filter (Ethereum address) must be encoded in abi.encode(address)
    /// format: 12 leading zero bytes, then the 20-byte address. This is exactly
    /// what the Noir circuit expects from the [u8; 32] adapter input.
    function _buildPublicInputs(
        PublicInputs calldata inputs,
        bytes32[_N_ZK_AGG] memory zkAgg
    ) internal pure returns (bytes32[] memory pub) {
        pub = new bytes32[](_N_PUB);
        uint256 idx;

        // Slot 0: n (u32 → single field element)
        pub[idx++] = bytes32(inputs.n);

        // Slots 1..32: accumulator_root bytes (most-significant byte first)
        bytes32 root = inputs.accumulatorRoot;
        for (uint256 i; i < 32; ++i) {
            pub[idx++] = bytes32(uint256(uint8(root[i])));
        }

        // Slots 33..64: capability_hash bytes
        bytes32 cap = inputs.capabilityHash;
        for (uint256 i; i < 32; ++i) {
            pub[idx++] = bytes32(uint256(uint8(cap[i])));
        }

        // Slots 65..96: adapter_filter encoded as abi.encode(address):
        //   bytes 0..11  → 0x00 (12 zero-padding bytes)
        //   bytes 12..31 → the 20-byte address
        bytes32 paddedAdapter = bytes32(uint256(uint160(inputs.adapterFilter)));
        for (uint256 i; i < 32; ++i) {
            pub[idx++] = bytes32(uint256(uint8(paddedAdapter[i])));
        }

        // Slot 97: min_return_bps (u64 → single field element)
        pub[idx++] = bytes32(inputs.minReturnBps);

        // Slots 98..113: ZK aggregation (opaque, prover-supplied)
        for (uint256 i; i < _N_ZK_AGG; ++i) {
            pub[idx++] = zkAgg[i];
        }
    }
}
