// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title ICircuit1Verifier
/// @notice Interface for the Circuit 1 (Selective Disclosure Proof) verifier.
///
/// Circuit 1 proves that N receipts accumulated under a specific capability:
///   (a) all hash correctly to the committed on-chain rolling root,
///   (b) all used a specified adapter (e.g. ClawloanRepayAdapter),
///   (c) all satisfy the capability's minReturnBps constraint (amountOut / amountIn >= floor).
///
/// In production: this interface is implemented by HonkCircuit1Verifier, which wraps the
///   Solidity contract generated by `bb write_solidity_verifier --scheme ultra_honk` from the
///   compiled Noir circuit. The proof is a UltraHonk (ZK Honk) proof.
///
/// In this PoC: implemented by MockCircuit1Verifier, which accepts a plaintext encoding of
///   the receipt hashes and nullifiers as the "proof" and validates them by replaying the
///   rolling hash computation. The mock replaces the ZK proof system but preserves the
///   identical public input schema that the real verifier will use.
///
/// Swapping from mock to production verifier requires only:
///   CreditVerifier.setVerifier(address(realVerifierContract))
/// No other changes to CreditVerifier or ReceiptAccumulator.

interface ICircuit1Verifier {

    /// @notice Public inputs that are committed alongside the proof.
    ///
    /// All fields are verified by the circuit:
    ///   - capabilityHash:   The receipts must all belong to this capability.
    ///   - n:                Exactly this many receipts are proven.
    ///   - accumulatorRoot:  The rolling root recomputed from the N receipts must equal this.
    ///                       CreditVerifier reads this from ReceiptAccumulator on-chain.
    ///   - adapterFilter:    Every receipt must have used this adapter.
    ///                       address(0) means no adapter filter.
    ///   - minReturnBps:     Every receipt must satisfy amountOut >= amountIn * minReturnBps / 10000.
    ///                       0 means no return floor.
    struct PublicInputs {
        bytes32 capabilityHash;
        uint256 n;
        bytes32 accumulatorRoot;
        address adapterFilter;
        uint256 minReturnBps;
    }

    /// @notice Verify a Circuit 1 selective disclosure proof.
    ///
    /// @param proof    In production (HonkCircuit1Verifier): abi.encode(bytes honkProof, bytes32[16] zkPublicInputs)
    ///                   where honkProof is the output of `bb prove --oracle_hash keccak`
    ///                   and zkPublicInputs are the 16 ZK aggregation elements from the public_inputs file.
    ///                 In MockCircuit1Verifier: abi.encode(bytes32[] receiptHashes, bytes32[] nullifiers,
    ///                   address[] adapters, uint256[] amountsIn, uint256[] amountsOut).
    /// @param inputs   Public inputs committed alongside the proof (semantic values; on-chain state read by caller).
    /// @return         True if the proof is valid and all constraints are satisfied.
    function verify(bytes calldata proof, PublicInputs calldata inputs) external returns (bool);
}
