// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ICircuit1Verifier} from "../../contracts/interfaces/ICircuit1Verifier.sol";

/// @title MockCircuit1Verifier
/// @notice Stand-in for the Noir-generated UltraHonk verifier for Circuit 1.
///
/// ─── What the Real Verifier Does ─────────────────────────────────────────────
///
/// The production verifier is generated by `nargo codegen-verifier` from the
/// Circuit 1 Noir source. It accepts:
///   - proof: ~2 KB opaque bytes (UltraHonk proof, no trusted setup)
///   - inputs: PublicInputs struct (capabilityHash, n, accumulatorRoot, adapterFilter, minReturnBps)
///
/// The circuit takes as PRIVATE inputs the N receipt hashes and nullifiers, and proves:
///   1. Rolling root recomputed from the receipts matches inputs.accumulatorRoot.
///   2. Every receipt used inputs.adapterFilter (if non-zero).
///   3. Every receipt satisfies amountOut >= amountIn * inputs.minReturnBps / 10000.
///
/// ─── What This Mock Does ─────────────────────────────────────────────────────
///
/// Instead of a ZK proof, the "proof" argument encodes the PRIVATE inputs in plaintext:
///   abi.encode(bytes32[] receiptHashes, bytes32[] nullifiers, uint256[] amountsIn, uint256[] amountsOut)
///
/// The mock verifier replicates Circuit 1's constraint checks in Solidity:
///   1. Recomputes the rolling root from the plaintext receipts.
///   2. Checks every receipt matches the adapterFilter (stored in the proof encoding via event data).
///   3. Checks every receipt satisfies minReturnBps (via amountsIn/amountsOut in the encoding).
///
/// The identical PublicInputs schema means swapping mock → real verifier requires ONLY:
///   CreditVerifier.setVerifier(address(realVerifierContract))
///
/// ─── Why This Is More Than a Trivial Mock ────────────────────────────────────
///
/// This mock verifier enforces the SAME cryptographic guarantee as the real one
/// with respect to the on-chain accumulator root:
///   - If the agent omits any receipt, the recomputed root won't match inputs.accumulatorRoot.
///   - If the agent forges a receipt, the hash won't match the nullifier chain.
///
/// The only difference from production: in this mock, the private inputs are revealed.
/// In production, they are hidden inside the ZK proof — the verifier never sees them,
/// yet still confirms all constraints are satisfied.

contract MockCircuit1Verifier is ICircuit1Verifier {

    /// @notice Verify a Circuit 1 selective disclosure proof.
    ///
    /// proof encoding (PoC plaintext substitute for ZK proof):
    ///   abi.encode(
    ///     bytes32[] receiptHashes,   // private in real circuit
    ///     bytes32[] nullifiers,      // private in real circuit
    ///     address[] adapters,        // private in real circuit — needed for adapter-filter constraint
    ///     uint256[] amountsIn,       // private in real circuit
    ///     uint256[] amountsOut       // private in real circuit
    ///   )
    ///
    /// Rolling root formula (must match ReceiptAccumulator.sol exactly):
    ///   root_i = keccak256(abi.encode(root_{i-1}, i, receiptHash_i, nullifier_i, adapter_i))
    ///   root_0 = bytes32(0)
    function verify(
        bytes calldata proof,
        PublicInputs calldata inputs
    ) external override returns (bool) {
        if (inputs.n == 0) return false;

        (
            bytes32[] memory receiptHashes,
            bytes32[] memory nullifiers,
            address[] memory adapters,
            uint256[] memory amountsIn,
            uint256[] memory amountsOut
        ) = abi.decode(proof, (bytes32[], bytes32[], address[], uint256[], uint256[]));

        // All arrays must have exactly n elements.
        if (receiptHashes.length != inputs.n) return false;
        if (nullifiers.length    != inputs.n) return false;
        if (adapters.length      != inputs.n) return false;
        if (amountsIn.length     != inputs.n) return false;
        if (amountsOut.length    != inputs.n) return false;

        bytes32 computedRoot = bytes32(0);

        for (uint256 i = 0; i < inputs.n; i++) {
            // ── Constraint 1: rolling root recomputation (adapter included) ───
            // Matches ReceiptAccumulator.sol exactly. Any omitted receipt or wrong
            // adapter causes computedRoot to diverge from inputs.accumulatorRoot.
            computedRoot = keccak256(abi.encode(
                computedRoot,
                i,
                receiptHashes[i],
                nullifiers[i],
                adapters[i]
            ));

            // ── Constraint 2: adapter filter ──────────────────────────────────
            // In the real circuit this is a field equality gate. Here we check directly.
            if (inputs.adapterFilter != address(0)) {
                if (adapters[i] != inputs.adapterFilter) return false;
            }

            // ── Constraint 3: minReturnBps ─────────────────────────────────────
            if (inputs.minReturnBps > 0) {
                uint256 floor = (amountsIn[i] * inputs.minReturnBps) / 10_000;
                if (amountsOut[i] < floor) return false;
            }
        }

        // The recomputed root must exactly match the on-chain accumulator root.
        return computedRoot == inputs.accumulatorRoot;
    }
}
