// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/lib/GF128.sol";
import "../src/lib/Transcript.sol";
import "../src/lib/MerkleLib.sol";
import "../src/Binius64Verifier.sol";
import "../src/lib/BiniusCompress.sol";
import "../src/lib/FRIFold.sol";

/// @title End-to-end test: real binius64 proof → Solidity verification
/// @notice Uses a proof fixture generated by `export-proof` from the Rust bench binary.
///         Validates step-by-step that the Solidity verifier produces the same Fiat-Shamir
///         challenges and intermediate values as the Rust verifier.
contract E2ETest is Test {
    using Transcript for Transcript.State;
    using GF128 for uint256;

    // From export-proof: constraint_system_params for Encumber circuit
    uint256 constant N_WITNESS_WORDS = 262144;
    uint256 constant N_CONSTANTS = 113;
    uint256 constant N_PUBLIC_WORDS = 13;
    uint256 constant N_AND_CONSTRAINTS = 141210;
    uint256 constant N_MUL_CONSTRAINTS = 0;
    uint256 constant LOG_INV_RATE = 1;
    uint256 constant N_FRI_QUERIES = 192;

    // From export-verifier-trace: golden reference values
    bytes32 constant EXPECTED_COMMITMENT = hex"1e57b62f90ef71c02a688906d7b48cfccef6a56ce247f2454e29fa91aa2ad148";
    uint256 constant EXPECTED_FIRST_CHALLENGE = 0x775fcaefca81186fef780efaa603661e;

    // Total public words after padding to power of 2 = 128
    uint256 constant PADDED_PUBLIC_WORDS = 128;

    Binius64Verifier public verifier;
    bytes public proofBytes;
    uint256[] public publicInputs;

    function setUp() public {
        // Deploy verifier
        verifier = new Binius64Verifier(
            Binius64Verifier.ConstraintSystemParams({
                nWitnessWords: N_WITNESS_WORDS,
                nPublicWords: N_PUBLIC_WORDS,
                logInvRate: LOG_INV_RATE,
                nFriQueries: N_FRI_QUERIES
            })
        );

        // Load proof from fixture
        string memory json = vm.readFile("test/fixtures/encumber_proof.json");
        string memory proofHex = vm.parseJsonString(json, ".proof_hex");
        proofBytes = vm.parseBytes(string.concat("0x", proofHex));

        // Load public inputs: the Rust verifier pads to 128 words (2^7)
        // First 113 are constants, next 13 are public I/O, rest are zeros
        // But public_inputs in the JSON are the full 128 padded words
        string[] memory pubHexArr = vm.parseJsonStringArray(json, ".public_inputs_hex");
        for (uint256 i = 0; i < pubHexArr.length; i++) {
            publicInputs.push(_parseU64Hex(pubHexArr[i]));
        }
    }

    /// @notice Test 1: Verify deployment and parameters
    function test_e2e_deployment() public view {
        (uint256 nw,,,) = verifier.params();
        assertEq(nw, N_WITNESS_WORDS);
    }

    /// @notice Test 2: Verify proof loading
    function test_e2e_proof_loaded() public view {
        assertTrue(proofBytes.length > 0, "proof bytes loaded");
        assertEq(proofBytes.length, 272288, "proof size matches");
        assertEq(publicInputs.length, PADDED_PUBLIC_WORDS, "128 public input words");
    }

    /// @notice Test 3: Verify the first 32 bytes of the proof are the commitment
    function test_e2e_commitment_bytes() public view {
        bytes32 firstBytes;
        assembly {
            let ptr := mload(0x40)
            let slot := proofBytes.slot
            let dataLoc := keccak256(add(slot, 0), 32)
            firstBytes := sload(dataLoc)
        }
        // Direct comparison using proof tape
        Transcript.State memory t = Transcript.init(proofBytes);
        _observePublicInputs(t, publicInputs);
        bytes32 commitment = t.messageBytes32();
        assertEq(commitment, EXPECTED_COMMITMENT, "commitment matches Rust");
    }

    /// @notice Test 4: Verify the first Fiat-Shamir challenge after observing
    ///         public inputs + reading commitment matches the Rust verifier
    function test_e2e_first_challenge() public view {
        Transcript.State memory t = Transcript.init(proofBytes);
        _observePublicInputs(t, publicInputs);
        t.messageBytes32(); // read commitment
        uint256 challenge = t.sampleGF128();
        assertEq(challenge, EXPECTED_FIRST_CHALLENGE, "first challenge matches Rust");
    }

    /// @notice Test 5: Verify that the transcript correctly processes
    ///         multiple GF128 elements from the proof tape
    function test_e2e_read_gf128_after_commitment() public view {
        Transcript.State memory t = Transcript.init(proofBytes);
        _observePublicInputs(t, publicInputs);
        t.messageBytes32(); // commitment

        // The next bytes are the IntMul reduction messages.
        // Since n_mul_constraints == 0, the IntMul phase is skipped.
        // The AND reduction is next (n_and_constraints == 141210).
        // First, the verifier samples `log_n_constraints - 3` challenges
        // for the zerocheck.
        // log2(141210) = 18 (ceil), so log_n_constraints = 18
        // zerocheck_challenges = 18 - 3 = 15 challenges sampled
        // But before that, the AND reduction reads univariate coefficients.
        // Let's just verify we can read GF128 elements without error.
        uint256 val = t.messageGF128();
        assertTrue(val != 0 || val == 0, "read GF128 from proof");
    }

    /// @notice Test 6: Gas benchmark for end-to-end transcript initialization
    function test_e2e_gas_bench_init() public {
        uint256 g0 = gasleft();
        Transcript.State memory t = Transcript.init(proofBytes);
        uint256 g1 = gasleft();
        emit log_named_uint("Transcript.init(272KB proof) gas", g0 - g1);

        g0 = gasleft();
        _observePublicInputs(t, publicInputs);
        g1 = gasleft();
        emit log_named_uint("Observe 128 public inputs gas", g0 - g1);

        g0 = gasleft();
        t.messageBytes32();
        g1 = gasleft();
        emit log_named_uint("Read commitment (32 bytes) gas", g0 - g1);

        g0 = gasleft();
        t.sampleGF128();
        g1 = gasleft();
        emit log_named_uint("Sample GF128 challenge gas", g0 - g1);
    }

    /// @notice Test 7: Verify the public inputs decode correctly
    function test_e2e_public_inputs() public view {
        // From Rust: public_word[0] = 0x0000000000000000 (zero)
        assertEq(publicInputs[0], 0);
        // public_word[1] = 0x0000000000000001
        assertEq(publicInputs[1], 1);
        // public_word[2] = 0x0000000000000002
        assertEq(publicInputs[2], 2);
    }

    /// @notice Test 8: Full verifier call — expects successful verification.
    ///
    /// Gas regression bound: the unoptimized Solidity verifier (no Yul/CLMUL,
    /// no batch inversion) consumes ~736M gas for the Encumber circuit proof.
    /// This is documented, expected, and feasible only inside Foundry tests
    /// (real block gas limits apply on-chain; the SP1 wrapper at ~280K is the
    /// production-viable path).  The bound below (900M) gives ~20% headroom for
    /// test overhead while catching any catastrophic regression that would double
    /// the cost.  Track the logged value across PRs to detect gradual drift.
    function test_e2e_verifier_call_smoke() public {
        uint256 gasBefore = gasleft();
        bool valid;
        bytes memory revertReason;
        bool reverted;

        try verifier.verify(proofBytes, publicInputs) returns (bool v) {
            valid = v;
        } catch (bytes memory reason) {
            revertReason = reason;
            reverted = true;
        }

        uint256 gasUsed = gasBefore - gasleft();
        emit log_named_uint("test_e2e_verifier_call_smoke gas", gasUsed);

        if (reverted) {
            emit log_named_bytes("revert reason", revertReason);
            assertTrue(false, "verification reverted");
        }
        assertTrue(valid, "full verification passed");

        // Regression gate: unoptimized verifier for Encumber circuit must stay
        // under 900M gas.  If this fires, an algorithmic regression was introduced.
        // Legitimate optimizations will reduce this number; update the bound then.
        assertLt(gasUsed, 900_000_000, "gas regression: unoptimized verifier exceeded 900M gas");
    }

    /// @notice Test 9: Verify the BiniusCompress function matches known Rust test vectors.
    function test_binius_compress_zeros() public pure {
        // Rust: compress(IV, [0; 64]) = baf78c8b60e294e88c6fa748f36cc802d779bd200670dca2d55a0ee75f0ba2b3
        bytes32 expected = hex"baf78c8b60e294e88c6fa748f36cc802d779bd200670dca2d55a0ee75f0ba2b3";
        bytes32 result = BiniusCompress.compress(bytes32(0), bytes32(0));
        assertEq(result, expected, "BiniusCompress(0,0) matches Rust");
    }

    /// @notice Test 10: Verify FRIFold.foldChunk matches Rust test vectors.
    function test_foldChunk_vector() public pure {
        uint256[] memory values = new uint256[](16);
        for (uint256 i = 0; i < 16; i++) values[i] = i + 1;

        uint256[] memory challenges = new uint256[](4);
        challenges[0] = 0x100;
        challenges[1] = 0x101;
        challenges[2] = 0x102;
        challenges[3] = 0x103;

        // chunk_index=0, log_len=14
        uint256 result0 = FRIFold.foldChunk(values, challenges, 14, 0);
        assertEq(result0, 0x46d3c0716b902d45e9eee7c00c1549ae, "foldChunk(0) matches Rust");

        // chunk_index=1 (need fresh values since foldChunk is pure with copies)
        uint256[] memory values2 = new uint256[](16);
        for (uint256 i = 0; i < 16; i++) values2[i] = i + 1;
        uint256 result1 = FRIFold.foldChunk(values2, challenges, 14, 1);
        assertEq(result1, 0x4b69161e81ae71954925bb040efb2a57, "foldChunk(1) matches Rust");
    }

    /// @notice Test 11: Verify FRIFold.foldInterleaved matches Rust test vectors.
    function test_foldInterleaved_vector() public {
        uint256[] memory values = new uint256[](16);
        for (uint256 i = 0; i < 16; i++) values[i] = i + 1;

        uint256[] memory challenges = new uint256[](4);
        challenges[0] = 0x200;
        challenges[1] = 0x201;
        challenges[2] = 0x202;
        challenges[3] = 0x203;

        // Debug: check eq_ind tensor against Rust values
        uint256[16] memory expectedTensor = [
            uint256(0x000000000000000000000010001c0c00),
            0x00000000000000000000001008180000,
            0x000000000000000000000010081c0206,
            0x000000000000000000000010001c0c00,
            0x00000000000000000000001008100800,
            0x00000000000000000000001000100000,
            0x00000000000000000000001000140004,
            0x00000000000000000000001008100800,
            0x00000000000000000000001008140a00,
            0x00000000000000000000001000140000,
            0x00000000000000000000001000100005,
            0x00000000000000000000001008140a00,
            0x000000000000000000000010001c0c00,
            0x00000000000000000000001008180000,
            0x000000000000000000000010081c0206,
            0x000000000000000000000010001c0c00
        ];

        // Compute individual products and accumulate for manual check
        uint256 manualResult = 0;
        for (uint256 i = 0; i < 16; i++) {
            uint256 prod = GF128.mul(values[i], expectedTensor[i]);
            manualResult ^= prod;
        }
        assertEq(manualResult, 0x00000000000000000000010041b0f213, "manual inner product matches Rust");

        // Debug: compute tensor in-place and check each element
        uint256[16] memory computedTensor;
        computedTensor[0] = 1;
        uint256 half = 1;
        for (uint256 k = 0; k < 4; k++) {
            uint256 r = challenges[k];
            uint256 oneMinusR = r ^ 1;
            for (uint256 j = half; j > 0;) {
                unchecked { j--; }
                uint256 base = computedTensor[j];
                computedTensor[2 * j] = GF128.mul(base, oneMinusR);
                computedTensor[2 * j + 1] = GF128.mul(base, r);
            }
            half <<= 1;
        }

        for (uint256 i = 0; i < 16; i++) {
            if (computedTensor[i] != expectedTensor[i]) {
                emit log_named_uint("tensor mismatch at index", i);
                emit log_named_uint("  computed", computedTensor[i]);
                emit log_named_uint("  expected", expectedTensor[i]);
            }
        }

        uint256 result = FRIFold.foldInterleaved(values, challenges);
        assertEq(result, 0x00000000000000000000010041b0f213, "foldInterleaved matches Rust");
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    function _observePublicInputs(
        Transcript.State memory t,
        uint256[] memory inputs
    ) internal pure {
        for (uint256 i = 0; i < inputs.length; i++) {
            bytes memory word = new bytes(8);
            uint256 val = inputs[i];
            assembly {
                let ptr := add(word, 32)
                mstore8(ptr, and(val, 0xff))
                mstore8(add(ptr, 1), and(shr(8, val), 0xff))
                mstore8(add(ptr, 2), and(shr(16, val), 0xff))
                mstore8(add(ptr, 3), and(shr(24, val), 0xff))
                mstore8(add(ptr, 4), and(shr(32, val), 0xff))
                mstore8(add(ptr, 5), and(shr(40, val), 0xff))
                mstore8(add(ptr, 6), and(shr(48, val), 0xff))
                mstore8(add(ptr, 7), and(shr(56, val), 0xff))
            }
            t.observe(word);
        }
    }

    function _parseU64Hex(string memory s) internal pure returns (uint256) {
        bytes memory b = bytes(s);
        uint256 result = 0;
        for (uint256 i = 0; i < b.length && i < 16; i++) {
            uint8 c = uint8(b[i]);
            uint8 nibble;
            if (c >= 48 && c <= 57) nibble = c - 48;
            else if (c >= 65 && c <= 70) nibble = c - 55;
            else if (c >= 97 && c <= 102) nibble = c - 87;
            else continue;
            result = (result << 4) | nibble;
        }
        return result;
    }
}
